api_platform:
    title: Medifax API
    version: 1.0.0
    formats:
        json:  ['application/json']
    docs_formats:
        html: ['text/html']
    defaults:
        pagination: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
